# Generated by Django 4.0.3 on 2022-03-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='profile_pics'),
        ),
    ]
