# Generated by Django 4.0.3 on 2022-03-22 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=10)),
                ('owner_name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateTimeField(auto_now_add=True)),
                ('loadtype', models.CharField(choices=[('1 kg - 1 Tonne', '1 kg - 1 Tonne'), ('1 Tonne - 3 Tonne', '1 Tonne - 3 Tonne'), ('3 Tonne - 5 Tonne', '3 Tonne - 5 Tonne')], max_length=200)),
                ('tf_number', models.CharField(max_length=200)),
                ('qty_m3', models.FloatField()),
                ('qty_ton', models.FloatField()),
                ('royalty_image', models.ImageField(upload_to='')),
                ('waybill_image', models.ImageField(upload_to='')),
                ('vehicle_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.vehicledetails')),
            ],
        ),
    ]
