# Generated by Django 4.0.3 on 2022-03-22 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_vehicledetails_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='loadtype',
            field=models.CharField(blank=True, choices=[('1 kg - 1 Tonne', '1 kg - 1 Tonne'), ('1 Tonne - 3 Tonne', '1 Tonne - 3 Tonne'), ('3 Tonne - 5 Tonne', '3 Tonne - 5 Tonne')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='loadtype1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.loadtype'),
        ),
    ]
