# Generated by Django 4.0.3 on 2022-03-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_loadtype_alter_tripdetails_loadtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadtype',
            name='load_type_rate_per_tonne',
            field=models.FloatField(blank=True, default=660),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='rate_per_tonne',
            field=models.CharField(default=250, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loadtype',
            name='load_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='royalty_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='vehicle_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.vehicledetails'),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='waybill_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='VehiclePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.FloatField()),
                ('amount_given', models.FloatField()),
                ('advance_given_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.loadtype')),
            ],
        ),
    ]
