# Generated by Django 4.0.3 on 2022-03-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_loadtype_load_type_rate_per_tonne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetails',
            name='loadtype',
        ),
    ]
