# Generated by Django 4.0.3 on 2022-03-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_tripdetails_loadtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripdetails',
            old_name='loadtype1',
            new_name='loadtype',
        ),
    ]
