# Generated by Django 4.0.3 on 2022-03-24 01:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_loadtype1_tripdetails_loadtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclepayments',
            name='advance_given_to',
        ),
        migrations.RemoveField(
            model_name='vehiclepayments',
            name='trip_date',
        ),
        migrations.AddField(
            model_name='vehiclepayments',
            name='advance_given_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclepayments',
            name='trip_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tripdetails'),
        ),
        migrations.AddField(
            model_name='vehiclepayments',
            name='vehicle_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.vehicledetails'),
        ),
    ]
