# Generated by Django 4.0.3 on 2022-03-24 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_vehiclepayments_advance_given_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclepayments',
            name='trip_details',
        ),
    ]
