# Generated by Django 4.0.3 on 2022-03-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_vehiclepayments_trip_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclepayments',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
