# Generated by Django 4.0.3 on 2022-03-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_vehiclepayments_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='trip_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayments',
            name='advance_given_date',
            field=models.DateField(blank=True),
        ),
    ]
