# Generated by Django 4.0.3 on 2022-03-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_tripdetails_trip_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='trip_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiclepayments',
            name='advance_given_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
