# Generated by Django 4.0.3 on 2022-03-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_tripdetails_trip_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclepayments',
            old_name='description',
            new_name='remarks',
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='trip_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehiclepayments',
            name='advance_given_date',
            field=models.DateField(),
        ),
    ]
