# Generated by Django 4.0.3 on 2022-03-27 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_description_vehiclepayments_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetails',
            name='driver_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='driver_phonenumber',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
