# Generated by Django 4.0.3 on 2022-03-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_companyname_quarrydetails_transporterdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetails',
            name='owner_name',
        ),
    ]
