# Generated by Django 4.0.3 on 2022-03-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_vehicledetails_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='load_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.loadtype'),
        ),
    ]
