# Generated by Django 4.0.3 on 2022-04-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_layerwisetripdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerwisetripdetails',
            name='send_to_review_by_malli',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
