# Generated by Django 4.0.3 on 2022-04-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_layerwisetripdetails_send_to_review_by_malli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerwisetripdetails',
            name='qty_ton',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='layerwisetripdetails',
            name='sendtomalli',
            field=models.CharField(choices=[(1, 'cofirm, Send to suresh'), (2, 'send back to engineer')], default=2, max_length=200),
        ),
        migrations.AlterField(
            model_name='layerwisetripdetails',
            name='verifiedbymalli',
            field=models.CharField(choices=[(1, 'cofirm, Send to suresh'), (2, 'send back to engineer')], default=2, max_length=200),
        ),
        migrations.AlterField(
            model_name='layerwisetripdetails',
            name='verifiedbysuresh',
            field=models.CharField(choices=[(1, 'cofirm, Send to suresh'), (2, 'send back to engineer')], default=2, max_length=200),
        ),
        migrations.AlterField(
            model_name='layerwisetripdetails',
            name='waybill_image_front',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
    ]
