# Generated by Django 4.0.3 on 2022-04-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_layerwisetripdetails_qty_ton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerwisetripdetails',
            name='sendtomalli',
            field=models.CharField(choices=[(1, 'cofirm, Send to suresh'), (2, 'send back to engineer'), (3, 'need some time')], default=3, max_length=200),
        ),
        migrations.AlterField(
            model_name='layerwisetripdetails',
            name='verifiedbymalli',
            field=models.CharField(choices=[(1, 'cofirm, Send to suresh'), (2, 'send back to engineer'), (3, 'need some time')], default=3, max_length=200),
        ),
        migrations.AlterField(
            model_name='layerwisetripdetails',
            name='verifiedbysuresh',
            field=models.CharField(choices=[(1, 'cofirm, Send to suresh'), (2, 'send back to engineer'), (3, 'need some time')], default=3, max_length=200),
        ),
    ]
