# Generated by Django 4.0.3 on 2022-04-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_layerwisetripdetails_sendtomalli_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerwisetripdetails',
            name='send_to_review_by_malli',
        ),
        migrations.AlterField(
            model_name='layerwisetripdetails',
            name='sendtomalli',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
