# Generated by Django 4.0.3 on 2022-04-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_remove_layerwisetripdetails_send_to_review_by_malli_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerwisetripdetails',
            name='sendtomalli',
        ),
        migrations.AlterField(
            model_name='layerwisetripdetails',
            name='verifiedbymalli',
            field=models.CharField(choices=[('Yes', 'Data is Correct, Send Forward'), ('No', 'Data is wrong, Send Back')], default='No', max_length=200),
        ),
        migrations.AlterField(
            model_name='layerwisetripdetails',
            name='verifiedbysuresh',
            field=models.CharField(choices=[('Yes', 'Data is Correct, Verify'), ('No', 'Data is wrong, Send back')], default='No', max_length=200),
        ),
    ]
