# Generated by Django 4.0.3 on 2022-04-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_remove_layerwisetripdetails_sendtomalli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerwisetripdetails',
            name='verifiedbyengineer',
            field=models.CharField(choices=[('Yes', 'Data is Correct, Send Forward'), ('No', 'Data is wrong, Send Back')], default='No', max_length=200),
        ),
    ]
