# Generated by Django 4.0.3 on 2022-04-03 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_layerwisetripdetails_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerwisetripdetails',
            name='vehicle_owner_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.transporterdetails'),
        ),
        migrations.AlterField(
            model_name='layerwisetripdetails',
            name='driver_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
