# Generated by Django 4.0.3 on 2022-04-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_city_country_person_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerwisetripdetails',
            name='trip_date',
            field=models.DateField(default='2022-03-20'),
        ),
        migrations.DeleteModel(
            name='VehiclePayments',
        ),
    ]
