# Generated by Django 4.0.3 on 2022-04-05 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_layerwisetripdetails_trip_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=200)),
                ('amount_given', models.FloatField()),
                ('advance_given_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.layerwisetripdetails')),
                ('vehicle_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.vehicledetails')),
            ],
        ),
    ]
