# Generated by Django 4.0.3 on 2022-04-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_abc'),
    ]

    operations = [
        migrations.CreateModel(
            name='exceldata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date1', models.DateField()),
                ('invoice_date', models.DateField()),
                ('invoice_number', models.IntegerField()),
                ('vehicle_number', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('qty_ton', models.FloatField()),
                ('rate_ton', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('tax_amount', models.FloatField()),
                ('total_amount_rounded', models.FloatField()),
                ('total_amount_decimal', models.FloatField()),
                ('round_off', models.FloatField()),
            ],
        ),
    ]
