# Generated by Django 4.0.3 on 2022-04-09 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_delete_abc_vehiclepayments_amount_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclepayments',
            name='advance_given_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
