# Generated by Django 4.0.3 on 2022-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_alter_vehiclepayments_advance_given_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporterdetails',
            name='rate_per_tonne',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
