# Generated by Django 4.0.3 on 2022-04-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_transporterdetails_rate_per_tonne'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepayments',
            name='amount_type',
            field=models.CharField(choices=[('Advance', 'Advance'), ('Payment', 'Payment')], default='Advance', max_length=200),
        ),
    ]
