# Generated by Django 4.0.3 on 2022-04-15 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_vehiclepayments_amount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetails',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='driver_name2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='driver_phone_number2',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
