# Generated by Django 4.0.3 on 2022-04-16 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_remove_vehicledetails_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarryPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_type', models.CharField(choices=[('Advance', 'Advance'), ('Payment', 'Payment')], default='Advance', max_length=200)),
                ('amount_given_date', models.DateField()),
                ('amount_given', models.FloatField()),
                ('remarks', models.CharField(max_length=200)),
                ('amount_receipt', models.ImageField(blank=True, upload_to='')),
                ('quarry_owner_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.quarrydetails')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_type', models.CharField(choices=[('Advance', 'Advance'), ('Payment', 'Payment')], default='Advance', max_length=200)),
                ('amount_received_date', models.DateField()),
                ('amount_received', models.FloatField()),
                ('remarks', models.CharField(max_length=200)),
                ('amount_receipt', models.ImageField(blank=True, upload_to='')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.companyname')),
            ],
        ),
    ]
