# Generated by Django 4.0.3 on 2022-04-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_quarrypayments_companypayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerwisetripdetails',
            name='approved',
            field=models.CharField(blank=True, default='No', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='layerwisetripdetails',
            name='forwarded',
            field=models.CharField(blank=True, default='No', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='layerwisetripdetails',
            name='verified',
            field=models.CharField(blank=True, default='No', max_length=200, null=True),
        ),
    ]
