# Generated by Django 4.0.3 on 2022-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_remove_layerwisetripdetails_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerwisetripdetails',
            name='comments',
            field=models.CharField(blank=True, choices=[('trip started', 'Trip Started'), ('trip completed', 'Trip Completed'), ('trip approved', 'Trip Approved'), ('trip verified', 'Trip Verified'), ('m3 wrong', 'M3 Wrong'), ('tf number wrong', 'TF Number Wrong'), ('ton wrong', 'Ton Wrong')], default='No Comments', max_length=200, null=True),
        ),
    ]
